RUN_MODE: DEBUG

APP:
  ENV: local
  PORT: 8888
  APP_NAME: potato
  APP_URL: 'http://localhost'

DATABASE:
  ENGINE: 'sqlite3'
  NAME: './potato.sqlite3'

LOG:
  LEVEL: 'DEBUG'
  FORMAT': '2006-01-02 15:04:05,99'
  PATH: "/var/log/potato/"
  FILE_NAME: "potato.log"
  SHOW_LINE: true
  MAX_BACKUPS: 5
  MAX_SIZE: 50  # 单位mb
  MAX_AGE: 30 # DAY
  COMPRESS: true


